### ISSUE TITLE
Be able to filter participants based on User.Name or User.Email

### ISSUE THREAD

**Issue by dylanherbig** [hoohacks/ideathon-registration#3]
HooHacks members should be able to quickly look up a participant to check them off. Create a simple front-end view that allows for filtering of a list of users based on their name or email. I believe that this can be done completely via front-end, but please change label if any back-end has to be completed. Coordinate with assignee of #1 to discuss how data should be pushed to the front-end.

**Comment by Akhil-Desai** [comment]
I can do this one

**Comment by Akhil-Desai** [comment]
Hi Dylan, I was just wondering where you wanted this feature to be created? Should it be somewhere on the ideathon website or make it in its own page

**Comment by dylanherbig** [comment]
> Hi Dylan, I was just wondering where you wanted this feature to be created? Should it be somewhere on the ideathon website or make it in its own page

Should be an additional subpage for the ideathon registration. Somewhat like /admin/participants. You will probably have to rearrange some of the files to allow for routing

**Comment by Akhil-Desai** [comment]
Hey Dylan I don't think there is an admin page or I'm not seeing it, should I just temporarily create it somewhere else then move it after

**Comment by dylanherbig** [comment]
Please create a temporary page. Also collaborate with #1 on the way data should be handled and represented

**Comment by param23403** [comment]
Done and merged
