### ISSUE TITLE
Integrate Google analytics into our registration system

### ISSUE THREAD

**Issue by dylanherbig** [hoohacks/ideathon-registration#5]
By utilizing Firebase as our database for the registration system, we also have the opportunity to be able to use Google Analytics for the data on how many sign-ups we get per day. I do not know how well it is integrated, but I do believe that we can improve it by fetching the google analytics data and displaying it within an authenticated admin view. Please create a handler to fetch the google analytics data and return it within a function for later usage

**Comment by param23403** [comment]
Done and merged
