### ISSUE TITLE
Design and integrate view for analytical data derived from Google analytics

### ISSUE THREAD

**Issue by dylanherbig** [hoohacks/ideathon-registration#6]
Coordinate with assignee from issue #5 on how to best display the google analytics data derived from handler. Also coordinate with the marketing team to ask for UI mock-ups on how to best display the information. There also exist some React plug-ins that we could potentially use, please look into them ensure compatibility with existing plug-ins which can be found in the package.json file within the root directory.

**Comment by elnora1** [comment]
I can do this one

**Comment by param23403** [comment]
Done and merged
